#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using the while loop

i=1
n=9

while [ $i -le 10 ]
do
  echo "Best School"
  if [ $i == $n ]
  then
  echo "Hi"
  fi

  i=$((i+1))
done
